apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowersales.fullname" . }}-secret
  labels:
    {{- include "flowersales.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.envSecret.DB_PASSWORD | default "" }}
  SESSION_SECRET: {{ .Values.envSecret.SESSION_SECRET | default "" }}
