apiVersion: v2
name: flowersales
description: A Helm chart for flowerSalesSystem
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - ecommerce
  - flowers
maintainers:
  - name: flowerSalesSystem Team
